name: app_privacy_guard
description: Blur in app switcher, Android secure flag, and iOS Dynamic Island watermark to protect sensitive UI.
version: 0.0.1
homepage: https://github.com/ShahzodAtabayev/app_privacy_guard
repository: https://github.com/ShahzodAtabayev/app_privacy_guard
issue_tracker: https://github.com/ShahzodAtabayev/app_privacy_guard/issues
topics:
  - privacy
  - security
  - blur
  - watermark
  - plugin

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.shahzod.app_privacy_guard
        pluginClass: AppPrivacyGuardPlugin
      ios:
        pluginClass: AppPrivacyGuardPlugin
